# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tita-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tita-Clone
pod ‘Then’
pod 'SnapKit'

end
